#!/bin/bash

# This script expect resources names with no spaces 

# Change to your own browser (firefox, chrome etc...)
BROWSER="surf"

ResourceName=`twingate resources | fzf | cut -f 1 -d ' '`

twingate auth $ResourceName | grep -m 1  https | cut -f 6 -d ' ' | xargs $BROWSER &
