#!/bin/bash

set -e

[[ $UID != 0 ]] && echo "This script requires root privilege" && exit

# IMPORTANT!!
# This script requires resources names with no spaces for ssh login

# Check for fzf
if ! command -v fzf >/dev/null 2>&1; then
  echo -e "\033[31mError: fzf is not installed. Please install it first.\033[0m"
  exit 1
fi

FZF_DEFAULT_OPTS="--tiebreak=length +i --height 30% --layout=reverse --border --pointer='→'" 
export FZF_DEFAULT_OPTS

user="administrator"
BROWSER="surf"

# -h
usage() {
  cat << EOF

  Usage: tg  -MODES 

  MODES:
    -h This help message
    -s Status 
    -l List resources
    -a Authenticate
    -ssh ssh into the selected resource
    -n Change network
EOF
}

# -l
listResources() {
  twingate resources | fzf --prompt="Select a Resource → "
}

# -a
Authenticate() {
  local ResourceName=`twingate resources | fzf | cut -f 1 -d ' '`
  twingate auth $ResourceName | grep -m 1  "https" | cut -f 6 -d ' ' | xargs -0 $BROWSER 
}

# -c (TODO: Have a list of usernames matching selected resource)
connect() {
  local host=`listResources | awk '{print $6}'` 
  ssh $user@$host
}

# -n
Network() {

  DA_networks=(
    "egesolucoes" 
    "egenetbr" 
    "custom"
  )

  local network=$(printf "%s\n" "${DA_networks[@]}" | fzf --prompt="Select Network: ")

  if [ -n "$network" ]; then
    if [ "$network" = "custom" ]; then
      read -p "Enter custom network: " network
    fi
    twingate config network "$network" && \

      $BROWSER `twingate status | grep -m 1 https`
  fi
  systemctl restart twingate
}

# Status command can return a url for authentication
# if twingate is online and with a network connected
# but not authenticated yet.
Status() {
 local login=`twingate status | grep https`
  if [ $login == "online" ]; then
    echo $login
  else
    surf $login
  fi
}

case "$1" in
  "-h") usage				    ;;
  "-s") Status	        ;;
  "-l") listResources   ;;
  "-a") Authenticate	  ;;
  "-c") connect				  ;;
  "-n") Network         ;;
  *) usage 					    ;;
esac
